// This file is auto-regenerated by the platform. We re-export the custom client
// so that any code (existing or future) importing from "@/integrations/supabase/client"
// uses the SAME Supabase instance and storage key as the rest of the app.
//
// Having two Supabase clients with different storageKeys causes them to fight
// over the auth session in localStorage, which manifests as random logouts on
// desktop. Re-exporting prevents that entirely.
export { supabase } from "./customClient";
