// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,          // localStorage requis pour PKCE (code_verifier doit survivre aux redirections d'onglets)
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,       // Détecte automatiquement le ?code= dans l'URL après confirmation email
    flowType: 'pkce',               // Sécurise le flow OAuth/email confirmation contre les attaques CSRF
  }
});
